# Generated by Django 5.1.6 on 2025-02-12 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("edicion", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=50)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("condiciones_intercambio", models.TextField()),
                (
                    "fecha_publicacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
